import type { SiteLocale } from "./localized-content";

// One row per shared homepage text node. Tuple arity makes missing locale copy
// a compile error; the English key also documents split phrases around links.
type Translations = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];
const rows = {
  "LaMaTeAm — Counter-Strike: Source Community": [
    "LaMaTeAm — komunita Counter-Strike: Source",
    "LaMaTeAm — komunita Counter-Strike: Source",
    "LaMaTeAm — społeczność Counter-Strike: Source",
    "LaMaTeAm — Counter-Strike: Source közösség",
    "LaMaTeAm — Counter-Strike: Source Community",
    "LaMaTeAm — спільнота Counter-Strike: Source",
    "LaMaTeAm — communauté Counter-Strike: Source",
  ],
  "Join LaMaTeAm CS:S — a fair EU classic rotation server with quiet-hours-friendly bots.":
    [
      "Připojte se na LaMaTeAm CS:S — férový evropský server s klasickými mapami a boty, kteří respektují noční klid.",
      "Pripojte sa na LaMaTeAm CS:S — férový európsky server s klasickými mapami a botmi, ktorí rešpektujú nočný pokoj.",
      "Dołącz do LaMaTeAm CS:S — uczciwego europejskiego serwera z klasycznymi mapami i botami szanującymi ciszę nocną.",
      "Csatlakozz a LaMaTeAm CS:S szerverhez — tisztességes európai szerver klasszikus pályákkal és a csendes órákhoz igazodó botokkal.",
      "Spiele auf LaMaTeAm CS:S — einem fairen EU-Server mit klassischen Maps und Bots, die Ruhezeiten berücksichtigen.",
      "Приєднуйтеся до LaMaTeAm CS:S — чесного європейського сервера з класичними картами та ботами, що враховують години тиші.",
      "Rejoignez LaMaTeAm CS:S — un serveur européen équitable avec des cartes classiques et des bots adaptés aux heures calmes.",
    ],
  "Counter-Strike: Source · CZ/SK community": [
    "Counter-Strike: Source · CZ/SK komunita",
    "Counter-Strike: Source · CZ/SK komunita",
    "Counter-Strike: Source · społeczność CZ/SK",
    "Counter-Strike: Source · CZ/SK közösség",
    "Counter-Strike: Source · CZ/SK-Community",
    "Counter-Strike: Source · спільнота CZ/SK",
    "Counter-Strike: Source · communauté CZ/SK",
  ],
  "Welcome to LaMaTeAm.": [
    "Vítejte na LaMaTeAm.",
    "Vitajte na LaMaTeAm.",
    "Witaj w LaMaTeAm.",
    "Üdv a LaMaTeAm oldalán!",
    "Willkommen bei LaMaTeAm.",
    "Ласкаво просимо до LaMaTeAm.",
    "Bienvenue chez LaMaTeAm.",
  ],
  "Back for another round? Classic maps, fair play and a place to reconnect.": [
    "Vrátíte se na další kolo? Klasické mapy, férová hra a místo pro opětovná setkání.",
    "Vraciate sa na ďalšie kolo? Klasické mapy, férová hra a miesto na opätovné stretnutia.",
    "Wracasz na kolejną rundę? Klasyczne mapy, uczciwa gra i miejsce, by znów się spotkać.",
    "Visszatérsz még egy körre? Klasszikus pályák, tisztességes játék és régi ismerősök.",
    "Noch eine Runde? Klassische Maps, Fairplay und ein Ort zum Wiedersehen.",
    "Повертаєтеся на ще один раунд? Класичні карти, чесна гра та місце для нових зустрічей.",
    "De retour pour une nouvelle manche ? Des cartes classiques, du fair-play et un lieu pour se retrouver.",
  ],
  "Join a round. Say hello.": [
    "Zahrajte si kolo. Pozdravte ostatní.",
    "Zahrajte si kolo. Pozdravte ostatných.",
    "Dołącz do rundy. Przywitaj się.",
    "Játssz egy kört. Köszönj be.",
    "Spiel eine Runde. Sag Hallo.",
    "Зіграйте раунд. Привітайтеся.",
    "Jouez une manche. Dites bonjour.",
  ],
  "Counter-Strike: Source, played together": [
    "Counter-Strike: Source hrajeme společně",
    "Counter-Strike: Source hráme spolu",
    "Counter-Strike: Source — gramy razem",
    "Counter-Strike: Source, közösen",
    "Counter-Strike: Source gemeinsam spielen",
    "Counter-Strike: Source — граємо разом",
    "Counter-Strike: Source, ensemble",
  ],
  "LaMaTeAm is a CZ/SK Counter-Strike: Source community on a European server. Join us for classic maps every evening.":
    [
      "LaMaTeAm je česká a slovenská komunita Counter-Strike: Source na evropském serveru. Každý večer si s námi zahrajte klasické mapy.",
      "LaMaTeAm je česká a slovenská komunita Counter-Strike: Source na európskom serveri. Každý večer si s nami zahrajte klasické mapy.",
      "LaMaTeAm to czesko-słowacka społeczność Counter-Strike: Source na europejskim serwerze. Graj z nami na klasycznych mapach każdego wieczoru.",
      "A LaMaTeAm egy cseh–szlovák Counter-Strike: Source közösség egy európai szerveren. Játssz velünk klasszikus pályákon minden este.",
      "LaMaTeAm ist eine tschechisch-slowakische Counter-Strike: Source Community auf einem europäischen Server. Spiele jeden Abend klassische Maps mit uns.",
      "LaMaTeAm — чесько-словацька спільнота Counter-Strike: Source на європейському сервері. Грайте з нами на класичних картах щовечора.",
      "LaMaTeAm est une communauté tchèque et slovaque de Counter-Strike: Source sur un serveur européen. Retrouvez-nous chaque soir sur des cartes classiques.",
    ],
  "We've been playing since the early days of Counter-Strike. Explore our": [
    "Hrajeme už od počátků Counter-Strike. Prohlédněte si naši",
    "Hráme už od začiatkov Counter-Strike. Pozrite si našu",
    "Gramy od początków Counter-Strike. Poznaj naszą",
    "A Counter-Strike kezdetei óta játszunk. Nézd meg a",
    "Wir spielen seit den Anfängen von Counter-Strike. Entdecke unsere",
    "Ми граємо з перших днів Counter-Strike. Перегляньте нашу",
    "Nous jouons depuis les débuts de Counter-Strike. Découvrez notre",
  ],
  "map rotation": [
    "nabídku map",
    "ponuku máp",
    "rotację map",
    "pályakínálatunkat",
    "Map-Rotation",
    "ротацію карт",
    "rotation de cartes",
  ],
  "and find a familiar favourite.": [
    "a najděte svou oblíbenou.",
    "a nájdite svoju obľúbenú.",
    "i znajdź swoją ulubioną.",
    "és találd meg a régi kedvencedet.",
    "und finde einen alten Favoriten wieder.",
    "та знайдіть улюблену.",
    "et retrouvez une de vos favorites.",
  ],
  "A place for new and returning players": [
    "Místo pro nové i vracející se hráče",
    "Miesto pre nových aj vracajúcich sa hráčov",
    "Miejsce dla nowych i powracających graczy",
    "Hely az új és visszatérő játékosoknak",
    "Ein Ort für neue Spieler und Rückkehrer",
    "Місце для нових гравців і тих, хто повертається",
    "Un lieu pour les nouveaux joueurs et ceux qui reviennent",
  ],
  "New here or returning to Source? Meet other players in": [
    "Jste tu poprvé nebo se vracíte ke Source? Seznamte se s ostatními na",
    "Ste tu prvýkrát alebo sa vraciate k Source? Spoznajte ostatných na",
    "Jesteś tu nowy lub wracasz do Source? Poznaj innych graczy na",
    "Új vagy itt, vagy visszatérsz a Source-hoz? Találkozz más játékosokkal itt:",
    "Neu hier oder zurück bei Source? Triff andere Spieler auf",
    "Ви тут уперше чи повертаєтеся до Source? Познайомтеся з іншими гравцями в",
    "Nouveau ici ou de retour sur Source ? Rencontrez les autres joueurs sur",
  ],
  "LaMaTeAm Discord ↗": [
    "Discordu LaMaTeAm ↗",
    "Discorde LaMaTeAm ↗",
    "Discordzie LaMaTeAm ↗",
    "LaMaTeAm Discord ↗",
    "LaMaTeAm Discord ↗",
    "Discord LaMaTeAm ↗",
    "Discord LaMaTeAm ↗",
  ],
  "Whether you're new or experienced, you're welcome to join us.": [
    "Ať jste začátečník nebo zkušený hráč, rádi vás přivítáme.",
    "Či ste začiatočník alebo skúsený hráč, radi vás privítame.",
    "Niezależnie od doświadczenia, zapraszamy do wspólnej gry.",
    "Akár kezdő vagy, akár tapasztalt játékos, szívesen látunk.",
    "Ob Anfänger oder erfahrener Spieler — du bist bei uns willkommen.",
    "Новачок ви чи досвідчений гравець — ми раді бачити вас.",
    "Débutant ou expérimenté, vous êtes le bienvenu parmi nous.",
  ],
  "Read the server rules": [
    "Přečtěte si pravidla serveru",
    "Prečítajte si pravidlá servera",
    "Przeczytaj zasady serwera",
    "Olvasd el a szerver szabályait",
    "Lies die Serverregeln",
    "Прочитайте правила сервера",
    "Lisez les règles du serveur",
  ],
  "before playing.": [
    "před hraním.",
    "pred hraním.",
    "przed grą.",
    "játék előtt.",
    "vor dem Spielen.",
    "перед грою.",
    "avant de jouer.",
  ],
  "Connect to the server": [
    "Připojit se na server",
    "Pripojiť sa na server",
    "Połącz się z serwerem",
    "Csatlakozás a szerverhez",
    "Mit dem Server verbinden",
    "Приєднатися до сервера",
    "Se connecter au serveur",
  ],
  "Server guides": [
    "Návody k serveru",
    "Návody k serveru",
    "Poradniki serwera",
    "Szerverútmutatók",
    "Server-Anleitungen",
    "Посібники сервера",
    "Guides du serveur",
  ],
  "Read the server rules before your next round": [
    "Před dalším kolem si přečtěte pravidla serveru",
    "Pred ďalším kolom si prečítajte pravidlá servera",
    "Przeczytaj zasady serwera przed kolejną rundą",
    "A következő kör előtt olvasd el a szerver szabályait",
    "Lies die Serverregeln vor deiner nächsten Runde",
    "Прочитайте правила сервера перед наступним раундом",
    "Lisez les règles du serveur avant votre prochaine manche",
  ],
  "Explore our LaMaTeAm Counter-Strike: Source guides.": [
    "Prohlédněte si naše návody pro LaMaTeAm Counter-Strike: Source.",
    "Pozrite si naše návody pre LaMaTeAm Counter-Strike: Source.",
    "Poznaj nasze poradniki LaMaTeAm Counter-Strike: Source.",
    "Böngészd a LaMaTeAm Counter-Strike: Source útmutatóit.",
    "Entdecke unsere Anleitungen für LaMaTeAm Counter-Strike: Source.",
    "Перегляньте наші посібники LaMaTeAm Counter-Strike: Source.",
    "Découvrez nos guides LaMaTeAm Counter-Strike: Source.",
  ],
  "Server rules.": [
    "Pravidla serveru.",
    "Pravidlá servera.",
    "Zasady serwera.",
    "A szerver szabályai.",
    "Serverregeln.",
    "Правила сервера.",
    "Règles du serveur.",
  ],
  "Current server maps.": [
    "Aktuální mapy serveru.",
    "Aktuálne mapy servera.",
    "Aktualne mapy serwera.",
    "A szerver jelenlegi pályái.",
    "Aktuelle Server-Maps.",
    "Поточні карти сервера.",
    "Cartes actuelles du serveur.",
  ],
  "CS:S money system.": [
    "Peněžní systém CS:S.",
    "Peňažný systém CS:S.",
    "System pieniędzy w CS:S.",
    "A CS:S pénzrendszere.",
    "Das Geldsystem in CS:S.",
    "Грошова система CS:S.",
    "Système monétaire de CS:S.",
  ],
  "Hitboxes, rates, and netgraph.": [
    "Hitboxy, síťové hodnoty a netgraph.",
    "Hitboxy, sieťové hodnoty a netgraph.",
    "Hitboksy, ustawienia sieciowe i netgraph.",
    "Találati zónák, hálózati beállítások és netgraph.",
    "Hitboxen, Netzwerkraten und Netgraph.",
    "Хітбокси, мережеві параметри та netgraph.",
    "Hitboxes, paramètres réseau et netgraph.",
  ],
  "FPS, radar, and sound fixes.": [
    "Opravy FPS, radaru a zvuku.",
    "Opravy FPS, radaru a zvuku.",
    "Poprawki FPS, radaru i dźwięku.",
    "FPS-, radar- és hangjavítások.",
    "Lösungen für FPS, Radar und Ton.",
    "Виправлення FPS, радара та звуку.",
    "Corrections des FPS, du radar et du son.",
  ],
  "Player commands and demos.": [
    "Příkazy pro hráče a dema.",
    "Príkazy pre hráčov a demá.",
    "Komendy graczy i dema.",
    "Játékosparancsok és demók.",
    "Spielerbefehle und Demos.",
    "Команди гравців і демозаписи.",
    "Commandes des joueurs et démos.",
  ],
  "Download SourceTV demos.": [
    "Stáhněte si dema SourceTV.",
    "Stiahnite si demá SourceTV.",
    "Pobierz dema SourceTV.",
    "SourceTV-demók letöltése.",
    "SourceTV-Demos herunterladen.",
    "Завантажте демозаписи SourceTV.",
    "Télécharger les démos SourceTV.",
  ],
  "Movement speed by weapon.": [
    "Rychlost pohybu podle zbraně.",
    "Rýchlosť pohybu podľa zbrane.",
    "Prędkość ruchu według broni.",
    "Mozgási sebesség fegyverenként.",
    "Bewegungsgeschwindigkeit je Waffe.",
    "Швидкість руху залежно від зброї.",
    "Vitesse de déplacement selon l’arme.",
  ],
  "Admins and admin rules.": [
    "Administrátoři a jejich pravidla.",
    "Administrátori a ich pravidlá.",
    "Administratorzy i ich zasady.",
    "Adminok és az adminok szabályai.",
    "Admins und Adminregeln.",
    "Адміністратори та їхні правила.",
    "Administrateurs et règles d’administration.",
  ],
  Banlist: [
    "Seznam banů",
    "Zoznam banov",
    "Lista banów",
    "Kitiltások",
    "Bannliste",
    "Список блокувань",
    "Liste des bannissements",
  ],
  "Server bans.": [
    "Bany na serveru.",
    "Bany na serveri.",
    "Bany na serwerze.",
    "Szerverkitiltások.",
    "Server-Banns.",
    "Блокування на сервері.",
    "Bannissements du serveur.",
  ],
  "Support the server.": [
    "Podpořte server.",
    "Podporte server.",
    "Wesprzyj serwer.",
    "Támogasd a szervert.",
    "Unterstütze den Server.",
    "Підтримайте сервер.",
    "Soutenez le serveur.",
  ],
  "Contact us.": [
    "Kontaktujte nás.",
    "Kontaktujte nás.",
    "Skontaktuj się z nami.",
    "Lépj kapcsolatba velünk.",
    "Kontaktiere uns.",
    "Зв’яжіться з нами.",
    "Contactez-nous.",
  ],
  Statistics: [
    "Statistiky",
    "Štatistiky",
    "Statystyki",
    "Statisztikák",
    "Statistiken",
    "Статистика",
    "Statistiques",
  ],
  "HLstatsX statistics.": [
    "Statistiky HLstatsX.",
    "Štatistiky HLstatsX.",
    "Statystyki HLstatsX.",
    "HLstatsX-statisztikák.",
    "HLstatsX-Statistiken.",
    "Статистика HLstatsX.",
    "Statistiques HLstatsX.",
  ],
  "LaMaTeAm server monitor": [
    "Monitor serveru LaMaTeAm",
    "Monitor servera LaMaTeAm",
    "Monitor serwera LaMaTeAm",
    "LaMaTeAm szerverfigyelő",
    "LaMaTeAm Serverstatus",
    "Монітор сервера LaMaTeAm",
    "État du serveur LaMaTeAm",
  ],
  "Approximate count; FakaHeda's feed may update about every five minutes.": [
    "Přibližný počet; zdroj FakaHeda se může aktualizovat přibližně každých pět minut.",
    "Približný počet; zdroj FakaHeda sa môže aktualizovať približne každých päť minút.",
    "Przybliżona liczba; dane FakaHeda mogą być aktualizowane co około pięć minut.",
    "Becsült szám; a FakaHeda adatai körülbelül ötpercenként frissülhetnek.",
    "Ungefähre Anzahl; die Daten von FakaHeda werden etwa alle fünf Minuten aktualisiert.",
    "Приблизна кількість; дані FakaHeda можуть оновлюватися приблизно кожні п’ять хвилин.",
    "Nombre approximatif ; les données de FakaHeda peuvent être actualisées environ toutes les cinq minutes.",
  ],
  "Checking player count…": [
    "Zjišťuji počet hráčů…",
    "Zisťujem počet hráčov…",
    "Sprawdzam liczbę graczy…",
    "Játékosszám lekérdezése…",
    "Spielerzahl wird geladen…",
    "Перевіряємо кількість гравців…",
    "Vérification du nombre de joueurs…",
  ],
  "Live LaMaTeAm players and current map": [
    "Aktuální hráči LaMaTeAm a mapa",
    "Aktuálni hráči LaMaTeAm a mapa",
    "Gracze LaMaTeAm na żywo i aktualna mapa",
    "Aktív LaMaTeAm-játékosok és jelenlegi pálya",
    "Aktuelle LaMaTeAm-Spieler und Map",
    "Гравці LaMaTeAm онлайн і поточна карта",
    "Joueurs LaMaTeAm en direct et carte actuelle",
  ],
  "Server address — select to copy": [
    "Adresa serveru — vyberte pro zkopírování",
    "Adresa servera — vyberte na skopírovanie",
    "Adres serwera — zaznacz, aby skopiować",
    "Szervercím — jelöld ki a másoláshoz",
    "Serveradresse — zum Kopieren auswählen",
    "Адреса сервера — виділіть для копіювання",
    "Adresse du serveur — sélectionnez pour copier",
  ],
  "Server address copied.": [
    "Adresa serveru zkopírována.",
    "Adresa servera skopírovaná.",
    "Adres serwera skopiowany.",
    "Szervercím másolva.",
    "Serveradresse kopiert.",
    "Адресу сервера скопійовано.",
    "Adresse du serveur copiée.",
  ],
  "Address selected. Use your device’s copy command.": [
    "Adresa je vybraná. Použijte příkaz kopírování svého zařízení.",
    "Adresa je vybraná. Použite príkaz kopírovania svojho zariadenia.",
    "Adres zaznaczony. Użyj polecenia kopiowania na swoim urządzeniu.",
    "A cím kijelölve. Használd az eszközöd másolási parancsát.",
    "Adresse ausgewählt. Nutze die Kopierfunktion deines Geräts.",
    "Адресу виділено. Скористайтеся командою копіювання на своєму пристрої.",
    "Adresse sélectionnée. Utilisez la commande de copie de votre appareil.",
  ],
} as const satisfies Record<string, Translations>;

export type HomeCopyKey = keyof typeof rows;
type HomeCopy = Record<HomeCopyKey, string>;
const localeOrder = ["cs", "sk", "pl", "hu", "de", "uk", "fr"] as const;
export const homeCopy = Object.fromEntries(
  (["en", ...localeOrder] as const).map((locale) => [
    locale,
    Object.fromEntries(
      Object.entries(rows).map(([key, values]) => [
        key,
        locale === "en" ? key : values[localeOrder.indexOf(locale)],
      ]),
    ),
  ]),
) as Record<SiteLocale, HomeCopy>;
